name: ml-db-delays
channels:
  - defaults
dependencies:
  - ipykernel
  - flask
  - flask-cors
  - scikit-learn
  - matplotlib
  - numpy
  - pandas
  - pytest
  - python-Levenshtein
  - xgboost
  - pip