name: ml-db-delays
channels:
  - defaults
dependencies:
  - pandas
  - scikit-learn
  - plotnine
  - numpy
  - seaborn
  - matplotlib
  - ipykernel
  - flask
  - pytest
  - pip
  - pip:
    - python-Levenshtein